PXP-8292 - Updating documentation on workspaces
uc-cdis/gen3.org pull request #142
Opened 2021-06-08 20:42 UTC by xritter1

Jira Ticket: https://ctds-planx.atlassian.net/browse/PXP-8292

### Improvements
Adding more documentation about workspaces.

2021-06-08 21:20 UTC, qiongl-CTDS approved these changes
LGTM

2021-06-08 22:11 UTC, cgmeyer approved these changes

2021-06-09 13:45 UTC, svburke commented on content/resources/user/analyze-data.md
> +git clone https://github.com/uc-cdis/gen3sdk-python.git
```suggestion
!git clone https://github.com/uc-cdis/gen3sdk-python.git
```

2021-06-09 14:15 UTC, svburke approved these changes

2021-06-09 14:15 UTC, qiongl-CTDS approved these changes

2021-06-14 14:20 UTC, gkuffel requested changes

2021-06-14 14:20 UTC, gkuffel commented on content/resources/user/submit-data.md
>  3. Find your project in the List of Projects and click 'Submit Data'
"List" shouldn't be capitalized.

2021-06-14 14:20 UTC, gkuffel commented on content/resources/user/submit-data.md
>  5. Fill in the required information (see Note below)
"Note should not be capitalized"

2021-06-14 14:26 UTC, qiongl-CTDS approved these changes
lgtm

2021-06-14 14:27 UTC, svburke approved these changes

2021-06-14 14:31 UTC, merged